name: 'dependabot-tickets'
description:
  'This action creates a FogBugz and AgilePlace Planview ticket for Dependabot pull requests.'
author: 'Ankura Consulting Group, LLC'

# Define your inputs here.
inputs:
  fogbugz_api_url:
    description: 'The URL of your FogBugz API'
    required: true
  fogbugz_token:
    description: 'Your FogBugz API token'
    required: true
  fogbugz_project:
    description: 'The name of your FogBugz Project'
    required: true
  fogbugz_subproject:
    description:
      'The subproject name of your FogBugz Project this is prepended to the Title because FB does
      not have subprojects'
    required: false
  fogbugz_category:
    description: 'The name of your FogBugz Category'
    required: true
  planview_api_url:
    description: 'The URL of your Planview API'
    required: true
  planview_auth:
    description: 'Your Planview API token'
    required: true
  planview_board_id:
    description: 'The ID of your Planview Board'
    required: true
  planview_lane_id:
    description: 'The ID of your Planview Lane to put the tickets'
    required: true
  planview_type_id:
    description: 'The type of ticket to create'
    required: true
  users:
    description: 'The user making the pull request. Set to "dependabot"'
    required: true
    default: 'dependabot'

# Define your outputs here.
outputs:
  fogbugz_id:
    description: 'The FogBugz case number created'
  planview_id:
    description: 'The Planview ticket id created'

runs:
  using: node20
  main: dist/index.js
