name: "Fogbugz Case Creator"
description: "Creates FogBugz cases."
inputs:
  api_url:
    required: true
    description: "API URL"
  token:
    required: true
    description: "API Token"
  project:
    required: true
    description: "Project"
  category:
    required: true
    description: "Category"
  title:
    required: true
    description: "Title"
  text:
    required: true
    description: "The body text for the case."
outputs:
  case_number:
    description: "The FogBugz case number."
runs:
  using: "node16"
  main: "dist/index.js"
